services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - TZ=Asia/Tokyo
      - NATURE_API_KEY=${NATURE_API_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"